# https://github.com/dart-lang/setup-dart

name: unittest

on:
  push:
    branches: [dev]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

  pull_request:
    branches: [dev]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

jobs:
  test:
    timeout-minutes: 9
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.12.0] # dart is null-safe since 2.12
        platform: [node, vm, chrome]
        #sdk: [stable, beta, dev, 2.12.0-29.10.beta]
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

#      - name: VM tests
#        run: dart test

      - name: Tests
        run: dart test --platform ${{ matrix.platform }}


  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.12.0
      - name: Install dependencies
        run: dart pub get
      - name: Analyze
        run: dart analyze lib --fatal-infos
      - name: Publish (dry run)
        run: dart pub publish --dry-run

  merge-to-staging:
    needs: [test, analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}

